Imports


In [110]:
import pandas as pd
import numpy as np
import seaborn as sns
import re
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
%matplotlib inline

Arrumando Preço

In [111]:
def arruma(preco):
    if pd.isnull(preco):
        return CellDF['PREÇO'].median()  
    preco = preco.strip().replace('R$', '', 1)
    preco = preco.replace('.', '_')
    preco = preco.replace(',', '.')
    preco = preco.replace('_', '')
    return np.float32(preco)

sconverter = {
    'PREÇO': arruma,
}



CellDF = pd.read_csv('resultado_parcial.csv', converters=sconverter)

print(CellDF.info())


CellDF = CellDF.drop(CellDF[CellDF['PREÇO'] >= 9000].index)

CellDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   MARCA           429 non-null    object 
 1   MODELO          423 non-null    object 
 2   SISTEMA_OP      431 non-null    object 
 3   REDE            431 non-null    object 
 4   MEMORIA_INT     425 non-null    float64
 5   RAM             391 non-null    float64
 6   RESOL CAM TRAS  374 non-null    float64
 7   GARANTIA        399 non-null    float64
 8   PESO            429 non-null    float64
 9   PREÇO           431 non-null    float32
dtypes: float32(1), float64(5), object(4)
memory usage: 32.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 422 entries, 0 to 430
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   MARCA           421 non-null    object 
 1   MODELO          414 non-null    object 


Dropando os nulo, fds

In [112]:
dfamor = CellDF.dropna()

Tratando Modelos Zaralhados

In [113]:
dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: x.upper().strip()) 
dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: 'SAMSUNG' if x == 'GALAXY S22 PLUS' else x)
dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: 'SAMSUNG' if x.find('SAMSUNG') != -1 else x)
dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: 'MOTOROLA' if x.find('MOTOROLA') != -1 else x)

dfamor 

/tmp/ipykernel_40498/3817290528.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: x.upper().strip())
/tmp/ipykernel_40498/3817290528.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfamor['MARCA']=  dfamor['MARCA'].apply(lambda x: 'SAMSUNG' if x == 'GALAXY S22 PLUS' else x)
/tmp/ipykernel_40498/3817290528.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value ins

MARCA        MODELO SISTEMA_OP REDE  MEMORIA_INT  RAM  RESOL CAM TRAS  \
0    MOTOROLA     MOTO G 52    Android   4G         64.0  4.0            48.0   
1     SAMSUNG   Galaxy A54     Android   5G        128.0  8.0            50.0   
2     SAMSUNG    Galaxy A14    Android   5G        128.0  8.0            50.0   
3     SAMSUNG   Galaxy A54     Android   5G        128.0  8.0            50.0   
4     SAMSUNG   Galaxy A04e    Android   4G         64.0  4.0            13.0   
..        ...           ...        ...  ...          ...  ...             ...   
424   SAMSUNG   Galaxy S22+    Android   5G        128.0  8.0            50.0   
425   SAMSUNG   Galaxy S22+    Android   5G        256.0  8.0            50.0   
426     APPLE     iPhone 13        IOS   5G        256.0  6.0            12.0   
427   SAMSUNG   Galaxy S22+    Android   5G        128.0  8.0            50.0   
428    REALME           C55    Android   4G         32.0  2.0             8.0   

     GARANTIA    PESO        PREÇO  
0        12.0   420.0  1089.000000  
1        12.0   332.0  1859.000000  
2        12.0   410.0  1129.000000  
3        12.0   334.0  1859.000000  
4        12.0   284.0   759.000000  
..        ...     ...          ...  
424      12.0   327.0  6299.100098  
425      12.0   327.0  6749.100098  
426      12.0  1000.0  7547.000000  
427      12.0   413.0  4949.100098  
428       3.0   190.0  1299.900024  

[309 rows x 10 columns]

In [114]:
dfamor['MARCA'].unique()

array(['MOTOROLA', 'SAMSUNG', 'APPLE', 'ASUS', 'POSITIVO', 'XIAOMI',
       'TCL', 'PHILCO', 'INFINIX', 'BLUE', 'MULTILASER', 'NOKIA', 'LG',
       'TECTOY', 'RED MOBILE', 'HUSKY SPORTS', 'REALME'], dtype=object)

Variável categórica -> numérica

In [115]:
print(dfamor['MARCA'].unique())
print(dfamor['SISTEMA_OP'].unique())
print(dfamor['REDE'].unique())

['MOTOROLA' 'SAMSUNG' 'APPLE' 'ASUS' 'POSITIVO' 'XIAOMI' 'TCL' 'PHILCO'
 'INFINIX' 'BLUE' 'MULTILASER' 'NOKIA' 'LG' 'TECTOY' 'RED MOBILE'
 'HUSKY SPORTS' 'REALME']
['Android' 'IOS']
['4G' '5G' '3G']


In [116]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse=False, categories='auto', dtype='int8')
dataframeenc = pd.DataFrame(encoder.fit_transform(dfamor[['MARCA','SISTEMA_OP']]))
columns = encoder.get_feature_names_out(['MARCA','SISTEMA_OP'])
dataframeenc.columns = columns
dataframeenc.index = dfamor.index
dfamorepaixao = pd.concat([dfamor, dataframeenc], axis=1)
dfamorepaixao = dfamorepaixao.drop(['MARCA', 'SISTEMA_OP', 'MODELO'],axis=1)

dfamorepaixao

/home/renanxm/.local/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


REDE  MEMORIA_INT  RAM  RESOL CAM TRAS  GARANTIA    PESO        PREÇO  \
0     4G         64.0  4.0            48.0      12.0   420.0  1089.000000   
1     5G        128.0  8.0            50.0      12.0   332.0  1859.000000   
2     5G        128.0  8.0            50.0      12.0   410.0  1129.000000   
3     5G        128.0  8.0            50.0      12.0   334.0  1859.000000   
4     4G         64.0  4.0            13.0      12.0   284.0   759.000000   
..   ...          ...  ...             ...       ...     ...          ...   
424   5G        128.0  8.0            50.0      12.0   327.0  6299.100098   
425   5G        256.0  8.0            50.0      12.0   327.0  6749.100098   
426   5G        256.0  6.0            12.0      12.0  1000.0  7547.000000   
427   5G        128.0  8.0            50.0      12.0   413.0  4949.100098   
428   4G         32.0  2.0             8.0       3.0   190.0  1299.900024   

     MARCA_APPLE  MARCA_ASUS  MARCA_BLUE  ...  MARCA_PHILCO  MARCA_POSITIVO  \
0              0           0           0  ...             0               0   
1              0           0           0  ...             0               0   
2              0           0           0  ...             0               0   
3              0           0           0  ...             0               0   
4              0           0           0  ...             0               0   
..           ...         ...         ...  ...           ...             ...   
424            0           0           0  ...             0               0   
425            0           0           0  ...             0               0   
426            1           0           0  ...             0               0   
427            0           0           0  ...             0               0   
428            0           0           0  ...             0               0   

     MARCA_REALME  MARCA_RED MOBILE  MARCA_SAMSUNG  MARCA_TCL  MARCA_TECTOY  \
0               0                 0              0          0             0   
1               0                 0              1          0             0   
2               0                 0              1          0             0   
3               0                 0              1          0             0   
4               0                 0              1          0             0   
..            ...               ...            ...        ...           ...   
424             0                 0              1          0             0   
425             0                 0              1          0             0   
426             0                 0              0          0             0   
427             0                 0              1          0             0   
428             1                 0              0          0             0   

     MARCA_XIAOMI  SISTEMA_OP_Android  SISTEMA_OP_IOS  
0               0                   1               0  
1               0                   1               0  
2               0                   1               0  
3               0                   1               0  
4               0                   1               0  
..            ...                 ...             ...  
424             0                   1               0  
425             0                   1               0  
426             0                   0               1  
427             0                   1               0  
428             0                   1               0  

[309 rows x 26 columns]

In [117]:
maping = {
    '3G': 0,
    '4G': 1,
    '5G': 2
}

dfamorepaixao['REDE'] = dfamorepaixao['REDE'].replace(maping)

dfamorepaixao['REDE'].unique()

array([1, 2, 0])

In [118]:
dfamorepaixao.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 309 entries, 0 to 428
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   REDE                309 non-null    int64  
 1   MEMORIA_INT         309 non-null    float64
 2   RAM                 309 non-null    float64
 3   RESOL CAM TRAS      309 non-null    float64
 4   GARANTIA            309 non-null    float64
 5   PESO                309 non-null    float64
 6   PREÇO               309 non-null    float32
 7   MARCA_APPLE         309 non-null    int8   
 8   MARCA_ASUS          309 non-null    int8   
 9   MARCA_BLUE          309 non-null    int8   
 10  MARCA_HUSKY SPORTS  309 non-null    int8   
 11  MARCA_INFINIX       309 non-null    int8   
 12  MARCA_LG            309 non-null    int8   
 13  MARCA_MOTOROLA      309 non-null    int8   
 14  MARCA_MULTILASER    309 non-null    int8   
 15  MARCA_NOKIA         309 non-null    int8   
 16  MARCA_PH

Treino e Teste + Normalização

In [119]:
dfamorepaixao.columns

x = (dfamorepaixao.drop('PREÇO', axis = 1)).to_numpy()
y = (dfamorepaixao['PREÇO']).to_numpy()

xtreino, xteste, ytreino, yteste = train_test_split(x,y, train_size=0.7)

In [120]:
Scaler = MinMaxScaler()
columns = xtreino
display(yteste)
xtreino = Scaler.fit_transform(xtreino)
xteste = Scaler.transform(xteste)


Scaleroutro = MinMaxScaler()
ytreino = Scaleroutro.fit_transform(ytreino.reshape(-1,1))
yteste = Scaleroutro.transform(yteste.reshape(-1,1))



display(ytreino)

array([4949.1 , 4949.1 , 3397.97, 4274.99, 2142.3 , 1415.6 , 1289.  ,
       2249.1 , 1299.  , 2969.1 ,  899.99, 2743.  , 7839.  ,  539.99,
       7598.1 , 3470.47,  759.  , 6749.1 , 5299.  , 2519.1 , 4949.  ,
       3149.99, 5509.99, 6209.1 , 2699.99, 5999.  , 4859.1 , 8260.92,
       6299.1 , 2998.  , 1101.05, 4679.1 ,  989.  ,  867.59, 3059.1 ,
       8299.  , 1202.94,  899.1 ,  853.1 ,  989.9 , 1999.99, 6999.  ,
       3361.49, 1399.  ,  853.1 , 1399.99, 1337.97, 1999.99, 1399.  ,
        899.99, 4799.  , 4762.4 , 7210.  , 6299.1 , 4274.99, 5199.  ,
       3597.37,  769.49,  989.9 ,  906.99,  333.55, 8999.1 , 2249.1 ,
       2199.  ,  899.99, 4199.  , 3199.  , 3199.  , 4409.1 , 1690.12,
        989.99,  899.99, 1079.99, 1545.  , 1349.99, 1166.6 , 1937.95,
       1129.  , 8299.  ,  815.  , 3289.99, 1069.  , 4299.  , 1543.69,
       2531.  , 1519.05, 6999.  , 5794.99, 1097.25,  375.21, 2294.1 ,
        854.99,  982.79], dtype=float32)

array([[0.11430542],
       [0.04477766],
       [0.07962771],
       [0.21365622],
       [0.04350568],
       [0.09139952],
       [0.53464323],
       [0.1500517 ],
       [0.4944157 ],
       [0.6794209 ],
       [0.21682179],
       [0.7979892 ],
       [0.6794209 ],
       [0.25542918],
       [0.0954487 ],
       [0.12761001],
       [0.04790302],
       [0.11075376],
       [0.10384925],
       [0.16694243],
       [0.37606573],
       [0.31068483],
       [0.5633575 ],
       [0.839021  ],
       [0.12109502],
       [0.09358726],
       [0.09110652],
       [0.1607147 ],
       [0.07616913],
       [0.24508792],
       [0.13133402],
       [0.12684017],
       [0.26185223],
       [0.1004125 ],
       [0.05318855],
       [0.02789843],
       [0.05318855],
       [0.44695392],
       [0.21198437],
       [0.05904745],
       [0.35884178],
       [0.11533955],
       [0.23475698],
       [0.04639779],
       [0.10374583],
       [0.37606573],
       [0.04228542],
       [0.079

In [121]:
model = LinearRegression()

model.fit(xtreino, ytreino)

prediction = model.predict(xteste)

yteste = Scaleroutro.inverse_transform(yteste)

prediction = Scaleroutro.inverse_transform(prediction)

mean_squared_error(yteste, prediction)


print(np.sqrt(mean_squared_error(yteste, prediction)))

1591.426574793603
